[build]
 command = "hugo"
 publish = “/Users/yasha/Desktop/Data_Science/jamesgammerman/public/”

[context.production.environment]
  HUGO_VERSION = "0.70"

# you can lock a version of hugo for a deploy preview
[context.deploy-preview.environment]
  HUGO_VERSION = "0.70"

# you can lock a version of hugo for a branch-deploy (other than previews)
[context.branch-deploy.environment]
  HUGO_VERSION = "0.70"